/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/attachments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Viewset for attachments. */
        get: operations["attachments_list"];
        put?: never;
        /** @description Viewset for attachments. */
        post: operations["attachments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Viewset for attachments. */
        get: operations["attachments_retrieve"];
        /** @description Viewset for attachments. */
        put: operations["attachments_update"];
        post?: never;
        /** @description Viewset for attachments. */
        delete: operations["attachments_destroy"];
        options?: never;
        head?: never;
        /** @description Viewset for attachments. */
        patch: operations["attachments_partial_update"];
        trace?: never;
    };
    "/api/v1/customer-companies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Viewset for customer companies. */
        get: operations["customer_companies_list"];
        put?: never;
        /** @description Create a customer company. */
        post: operations["customer_companies_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-companies/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Viewset for customer companies. */
        get: operations["customer_companies_retrieve"];
        /** @description Update a customer company. */
        put: operations["customer_companies_update"];
        post?: never;
        /** @description Viewset for customer companies. */
        delete: operations["customer_companies_destroy"];
        options?: never;
        head?: never;
        /** @description Viewset for customer companies. */
        patch: operations["customer_companies_partial_update"];
        trace?: never;
    };
    "/api/v1/drivers/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search users. */
        get: operations["drivers_search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the profile. */
        get: operations["profile_retrieve"];
        /** @description Update the profile. */
        put: operations["profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema.json/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json */
        get: operations["schema.json_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Viewset for shipments. */
        get: operations["shipments_list"];
        put?: never;
        /** @description Create a shipment. */
        post: operations["shipments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Viewset for shipments. */
        get: operations["shipments_retrieve"];
        /** @description Viewset for shipments. */
        put: operations["shipments_update"];
        post?: never;
        /** @description Viewset for shipments. */
        delete: operations["shipments_destroy"];
        options?: never;
        head?: never;
        /** @description Viewset for shipments. */
        patch: operations["shipments_partial_update"];
        trace?: never;
    };
    "/api/v1/shipments/{uuid}/archive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Archive a shipment. */
        put: operations["shipments_archive_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{uuid}/attachments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List attachments for a shipment. */
        get: operations["shipments_attachments_list"];
        put?: never;
        /** @description List attachments for a shipment. */
        post: operations["shipments_attachments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{uuid}/driver/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Assign a driver to a shipment. */
        put: operations["shipments_driver_update"];
        post?: never;
        /** @description Assign a driver to a shipment. */
        delete: operations["shipments_driver_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{uuid}/reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of shipments for the authenticated user. */
        get: operations["shipments_reports_list"];
        put?: never;
        /** @description Get a list of shipments for the authenticated user. */
        post: operations["shipments_reports_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/driver-statistics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get driver shipment statistics including total assigned, in progress, and completed. */
        get: operations["shipments_driver_statistics_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials. */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid. */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/delete-account/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a user account. */
        delete: operations["users_delete_account_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the current user. */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register a new user. */
        post: operations["users_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search users. */
        get: operations["users_search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Serializer for attachments. */
        Attachment: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: uri */
            file: string;
            is_public?: boolean;
            /** @description The stage of the shipment this attachment is associated with
             *
             *     * `LOADING` - Loading File
             *     * `UNLOADING` - Unloading File
             *     * `OTHER` - Other File */
            stage?: components["schemas"]["Stage84fEnum"];
            /** @description The type of media this attachment is
             *
             *     * `PHOTO` - Photo
             *     * `DOCUMENT` - Document
             *     * `OTHER` - Other */
            media_type?: components["schemas"]["MediaTypeEnum"];
            created_by: number;
            updated_by: number;
            /** Format: uuid */
            shipment: string;
        };
        /**
         * @description * `PHOTO` - Photo
         *     * `DOCUMENT` - Document
         *     * `OTHER` - Other
         * @enum {string}
         */
        AttachmentMediaTypeEnum: "PHOTO" | "DOCUMENT" | "OTHER";
        /**
         * @description * `LOADING` - Loading File
         *     * `UNLOADING` - Unloading File
         *     * `OTHER` - Other File
         * @enum {string}
         */
        AttachmentStageEnum: "LOADING" | "UNLOADING" | "OTHER";
        /** @description Serializer for customer companies. */
        CustomerCompany: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            name: string;
            created_by: number;
            readonly updated_by: number;
        };
        /** @description Serializer for driver shipment statistics. */
        DriverStatistics: {
            readonly total_assigned: number;
            readonly total_in_progress: number;
            readonly total_completed: number;
        };
        /** @description Serializer for reading attachments. */
        ListAttachment: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: uri */
            readonly file: string;
            readonly is_public: boolean;
            readonly stage: components["schemas"]["Stage84fEnum"];
            readonly media_type: components["schemas"]["MediaTypeEnum"];
            /** Format: date-time */
            readonly created_at: string;
            readonly created_by: components["schemas"]["ReadUser"];
        };
        /**
         * @description * `PHOTO` - Photo
         *     * `DOCUMENT` - Document
         *     * `OTHER` - Other
         * @enum {string}
         */
        MediaTypeEnum: "PHOTO" | "DOCUMENT" | "OTHER";
        PaginatedCustomerCompanyList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CustomerCompany"][];
        };
        PaginatedListAttachmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ListAttachment"][];
        };
        PaginatedShipmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Shipment"][];
        };
        PaginatedShipmentReportList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ShipmentReport"][];
        };
        /** @description Serializer for attachments. */
        PatchedAttachment: {
            /** Format: uuid */
            readonly uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            /** Format: uri */
            file?: string;
            is_public?: boolean;
            /** @description The stage of the shipment this attachment is associated with
             *
             *     * `LOADING` - Loading File
             *     * `UNLOADING` - Unloading File
             *     * `OTHER` - Other File */
            stage?: components["schemas"]["Stage84fEnum"];
            /** @description The type of media this attachment is
             *
             *     * `PHOTO` - Photo
             *     * `DOCUMENT` - Document
             *     * `OTHER` - Other */
            media_type?: components["schemas"]["MediaTypeEnum"];
            created_by?: number;
            updated_by?: number;
            /** Format: uuid */
            shipment?: string;
        };
        /** @description Serializer for customer companies. */
        PatchedCustomerCompany: {
            /** Format: uuid */
            readonly uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            name?: string;
            created_by?: number;
            readonly updated_by?: number;
        };
        /** @description Serializer for shipments. */
        PatchedShipment: {
            /** Format: uuid */
            readonly uuid?: string;
            readonly company?: components["schemas"]["CustomerCompany"];
            readonly driver?: components["schemas"]["ReadUser"];
            readonly user?: components["schemas"]["ReadUser"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            cmr_code?: string;
            type?: components["schemas"]["TypeEnum"];
            status?: components["schemas"]["StatusEnum"];
            is_archived?: boolean;
        };
        /** @description Serializer for profiles. */
        Profile: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            phone_number: string;
            /** @description Whether the user is a driver */
            is_driver?: boolean;
            user: number;
        };
        /** @description Serializer for reading a user. */
        ReadUser: {
            readonly id: number;
            /**
             * Email address
             * Format: email
             */
            email?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** @description Get the name of the user. */
            readonly name: string;
            /** @description Get the is_driver of the user. */
            readonly is_driver: boolean;
        };
        /** @description Serializer for shipments. */
        Shipment: {
            /** Format: uuid */
            readonly uuid: string;
            readonly company: components["schemas"]["CustomerCompany"];
            readonly driver: components["schemas"]["ReadUser"];
            readonly user: components["schemas"]["ReadUser"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            cmr_code: string;
            type?: components["schemas"]["TypeEnum"];
            status?: components["schemas"]["StatusEnum"];
            is_archived?: boolean;
        };
        /** @description Serializer for ShipmentReport model. */
        ShipmentReport: {
            /** Format: uuid */
            readonly uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: uri */
            file?: string | null;
            stage?: components["schemas"]["ShipmentReportStageEnum"];
            /** Format: uuid */
            shipment: string;
        };
        /**
         * @description * `LOADING` - Loading
         *     * `UNLOADING` - Unloading
         * @enum {string}
         */
        ShipmentReportStageEnum: "LOADING" | "UNLOADING";
        /**
         * @description * `LOADING` - Loading File
         *     * `UNLOADING` - Unloading File
         *     * `OTHER` - Other File
         * @enum {string}
         */
        Stage84fEnum: "LOADING" | "UNLOADING" | "OTHER";
        /**
         * @description * `IN_PROGRESS` - In Progress
         *     * `COMPLETED` - Completed
         *     * `CANCELLED` - Cancelled
         * @enum {string}
         */
        StatusEnum: "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /**
         * @description * `INBOUND` - Inbound
         *     * `OUTBOUND` - Outbound
         * @enum {string}
         */
        TypeEnum: "INBOUND" | "OUTBOUND";
        /** @description Serializer for uploading attachments. */
        UploadAttachment: {
            attachment_stage: components["schemas"]["AttachmentStageEnum"];
            attachment_media_type: components["schemas"]["AttachmentMediaTypeEnum"];
            /** Format: uri */
            attachment_file: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attachments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"][];
                };
            };
        };
    };
    attachments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attachment"];
                "application/x-www-form-urlencoded": components["schemas"]["Attachment"];
                "multipart/form-data": components["schemas"]["Attachment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    attachments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    attachments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attachment"];
                "application/x-www-form-urlencoded": components["schemas"]["Attachment"];
                "multipart/form-data": components["schemas"]["Attachment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    attachments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attachments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attachment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAttachment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAttachment"];
                "multipart/form-data": components["schemas"]["PatchedAttachment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
        };
    };
    customer_companies_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCustomerCompanyList"];
                };
            };
        };
    };
    customer_companies_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCompany"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerCompany"];
                "multipart/form-data": components["schemas"]["CustomerCompany"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerCompany"];
                };
            };
        };
    };
    customer_companies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Customer Company. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerCompany"];
                };
            };
        };
    };
    customer_companies_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Customer Company. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCompany"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerCompany"];
                "multipart/form-data": components["schemas"]["CustomerCompany"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerCompany"];
                };
            };
        };
    };
    customer_companies_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Customer Company. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customer_companies_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Customer Company. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomerCompany"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomerCompany"];
                "multipart/form-data": components["schemas"]["PatchedCustomerCompany"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerCompany"];
                };
            };
        };
    };
    drivers_search_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
                "application/x-www-form-urlencoded": components["schemas"]["Profile"];
                "multipart/form-data": components["schemas"]["Profile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    "schema.json_retrieve": {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    shipments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedShipmentList"];
                };
            };
        };
    };
    shipments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Shipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Shipment"];
                "multipart/form-data": components["schemas"]["Shipment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
        };
    };
    shipments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
        };
    };
    shipments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Shipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Shipment"];
                "multipart/form-data": components["schemas"]["Shipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
        };
    };
    shipments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shipments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedShipment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedShipment"];
                "multipart/form-data": components["schemas"]["PatchedShipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
        };
    };
    shipments_archive_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Shipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Shipment"];
                "multipart/form-data": components["schemas"]["Shipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
        };
    };
    shipments_attachments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListAttachmentList"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAttachment"];
                };
            };
        };
    };
    shipments_attachments_create: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Shipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Shipment"];
                "multipart/form-data": components["schemas"]["Shipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListAttachmentList"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAttachment"];
                };
            };
        };
    };
    shipments_driver_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Shipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Shipment"];
                "multipart/form-data": components["schemas"]["Shipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
        };
    };
    shipments_driver_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shipments_reports_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedShipmentReportList"];
                };
            };
        };
    };
    shipments_reports_create: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description A UUID string identifying this Shipment. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Shipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Shipment"];
                "multipart/form-data": components["schemas"]["Shipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedShipmentReportList"];
                };
            };
        };
    };
    shipments_driver_statistics_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverStatistics"];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    users_delete_account_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_search_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
